#!/bin/sh

if [ $1 ]; then
    VERSION=$1
else
    VERSION="test"
fi

VOLUME="MPlayerOSX Extended"
FILES=./build/Release
DMG="releases/MPlayer-OSX-Extended_$VERSION.dmg"

# Create tmp disk image
hdiutil create "$DMG" -srcfolder $FILES/ -ov -volname "$VOLUME"

