#!/bin/sh
# MPlayer OSX create dmg script
# Adrian Stutz 2008

# *** CONFIG
volume_name="MPlayerOSX Extended"
source_dir="/Users/adrian/dev/mplayer/mplayerosx/build/Release"
output_dir="/Users/adrian/dev/mplayer/mplayerosx/releases"

# *** SET VERSION
if [ $1 ]; then
    version=$1
else
    version="test"
fi

# *** SET DMG NAME
dmg_name="MPlayer-OSX-Extended_${version}.dmg"

# *** CREATE
hdiutil create "$output_dir/$dmg_name" -srcfolder $source_dir -ov -volname "$volume_name"