#!/bin/sh
# MPlayer OSX binary install script
# Adrian Stutz 2008

# *** CONFIG
mplayerosx_path="/Users/adrian/dev/mplayer/mplayerosx/"

if [ ! -n "$1" ]; then
	echo "usage: ./install.sh folder"
	exit 1
fi

if [ ! -d "$mplayerosx_path/External_Binaries" ]; then
	echo "Invalid mplayerosx path!"
	exit 1
fi

echo "Searching $1 for binaries..."

# Copy universal binary (mplayer.ub) to mplayer.app
if [ -f "$1/mplayer.ub" ]; then
	cp "$1/mplayer.ub" "$mplayerosx_path/External_Binaries/mplayer.app/Contents/MacOS/mplayer"
	echo "mplayer.ub copied to mplayer.app/Contents/MacOS/mplayer"
fi

# Copy ppc g3 version (mplayer.ppcg3) to mplayer_noaltivec.app
if [ -f "$1/mplayer.ppcg3" ]; then
	cp "$1/mplayer.ppcg3" "$mplayerosx_path/External_Binaries/mplayer_noaltivec.app/Contents/MacOS/mplayer"
	echo "mplayer.ppcg3 copied to mplayer_noaltivec.app/Contents/MacOS/mplayer"
fi

# Touch the folder to make XCode copy the new binaries
touch "$mplayerosx_path/External_Binaries"

echo "Finished."